// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Stable error codes shared by iOS and Android, so Dart can decide between
/// retry, step-up or a user message without comparing strings.
enum LivenessErrorCode {
  unknown,
  sessionNotFound,
  accessDenied,
  cameraPermissionDenied,
  cameraNotAvailable,
  sessionInterrupted,
  sessionTimedOut,
  faceCheckFailed,
  unsupportedChallenge,
  userCancelled,
  videoEncoding,
  serviceError,
  sdkNotLinked,
  credentialsUnavailable,
  platformNotSupported,
}

/// Temporary AWS credentials handed to the native liveness SDK, which signs the
/// WebSocket to Amazon Rekognition directly. The SDK fetches them once per
/// session and never refreshes, so the real expiration must travel with them.
class LivenessCredentialsMessage {
  LivenessCredentialsMessage({
    required this.accessKeyId,
    required this.secretAccessKey,
    required this.sessionToken,
    required this.expirationEpochSeconds,
  });

  String accessKeyId;

  String secretAccessKey;

  String sessionToken;

  int expirationEpochSeconds;

  List<Object?> _toList() {
    return <Object?>[
      accessKeyId,
      secretAccessKey,
      sessionToken,
      expirationEpochSeconds,
    ];
  }

  Object encode() {
    return _toList();  }

  static LivenessCredentialsMessage decode(Object result) {
    result as List<Object?>;
    return LivenessCredentialsMessage(
      accessKeyId: result[0]! as String,
      secretAccessKey: result[1]! as String,
      sessionToken: result[2]! as String,
      expirationEpochSeconds: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LivenessCredentialsMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(accessKeyId, other.accessKeyId) && _deepEquals(secretAccessKey, other.secretAccessKey) && _deepEquals(sessionToken, other.sessionToken) && _deepEquals(expirationEpochSeconds, other.expirationEpochSeconds);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'LivenessCredentialsMessage(accessKeyId: $accessKeyId, secretAccessKey: $secretAccessKey, sessionToken: $sessionToken, expirationEpochSeconds: $expirationEpochSeconds)';
  }
}

/// The native SDK finished streaming. It carries no verdict on either
/// platform: the backend reads the result with GetFaceLivenessSessionResults.
class LivenessCompletionMessage {
  LivenessCompletionMessage({
    required this.sessionId,
  });

  String sessionId;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
    ];
  }

  Object encode() {
    return _toList();  }

  static LivenessCompletionMessage decode(Object result) {
    result as List<Object?>;
    return LivenessCompletionMessage(
      sessionId: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LivenessCompletionMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'LivenessCompletionMessage(sessionId: $sessionId)';
  }
}

/// A native-side failure (SDK error, cancellation, or missing dependency).
class LivenessErrorMessage {
  LivenessErrorMessage({
    required this.code,
    required this.message,
  });

  LivenessErrorCode code;

  String message;

  List<Object?> _toList() {
    return <Object?>[
      code,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static LivenessErrorMessage decode(Object result) {
    result as List<Object?>;
    return LivenessErrorMessage(
      code: result[0]! as LivenessErrorCode,
      message: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LivenessErrorMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(code, other.code) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'LivenessErrorMessage(code: $code, message: $message)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is LivenessErrorCode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is LivenessCredentialsMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is LivenessCompletionMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is LivenessErrorMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : LivenessErrorCode.values[value];
      case 130:
        return LivenessCredentialsMessage.decode(readValue(buffer)!);
      case 131:
        return LivenessCompletionMessage.decode(readValue(buffer)!);
      case 132:
        return LivenessErrorMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Dart -> native. Called once, after the platform view is created and
/// credentials have been fetched. Receiving credentials is the signal for the
/// native side to present the liveness detector.
class LivenessHostApi {
  /// Constructor for [LivenessHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LivenessHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> setCredentials(LivenessCredentialsMessage credentials) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.rekognition_liveness.LivenessHostApi.setCredentials$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[credentials]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// Dart -> native, app-wide (no channel suffix). The Android SDK does not ask
/// for the camera permission itself, so the app asks before showing the view.
class LivenessPermissionApi {
  /// Constructor for [LivenessPermissionApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LivenessPermissionApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> requestCameraPermission() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.rekognition_liveness.LivenessPermissionApi.requestCameraPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }
}

/// Native -> Dart. Terminal callbacks; exactly one fires per session.
abstract class LivenessFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onComplete(LivenessCompletionMessage completion);

  void onError(LivenessErrorMessage error);

  static void setUp(LivenessFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.rekognition_liveness.LivenessFlutterApi.onComplete$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final LivenessCompletionMessage arg_completion = args[0]! as LivenessCompletionMessage;
          try {
            api.onComplete(arg_completion);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.rekognition_liveness.LivenessFlutterApi.onError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final LivenessErrorMessage arg_error = args[0]! as LivenessErrorMessage;
          try {
            api.onError(arg_error);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
