// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Stable error codes shared by iOS and Android, so Dart can decide between
/// retry, step-up or a user message without comparing strings.
enum LivenessErrorCode: Int, CaseIterable {
  case unknown = 0
  case sessionNotFound = 1
  case accessDenied = 2
  case cameraPermissionDenied = 3
  case cameraNotAvailable = 4
  case sessionInterrupted = 5
  case sessionTimedOut = 6
  case faceCheckFailed = 7
  case unsupportedChallenge = 8
  case userCancelled = 9
  case videoEncoding = 10
  case serviceError = 11
  case sdkNotLinked = 12
  case credentialsUnavailable = 13
  case platformNotSupported = 14
}

/// Temporary AWS credentials handed to the native liveness SDK, which signs the
/// WebSocket to Amazon Rekognition directly. The SDK fetches them once per
/// session and never refreshes, so the real expiration must travel with them.
///
/// Generated class from Pigeon that represents data sent in messages.
struct LivenessCredentialsMessage: Hashable, CustomStringConvertible {
  var accessKeyId: String
  var secretAccessKey: String
  var sessionToken: String
  var expirationEpochSeconds: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LivenessCredentialsMessage? {
    let accessKeyId = pigeonVar_list[0] as! String
    let secretAccessKey = pigeonVar_list[1] as! String
    let sessionToken = pigeonVar_list[2] as! String
    let expirationEpochSeconds = pigeonVar_list[3] as! Int64

    return LivenessCredentialsMessage(
      accessKeyId: accessKeyId,
      secretAccessKey: secretAccessKey,
      sessionToken: sessionToken,
      expirationEpochSeconds: expirationEpochSeconds
    )
  }
  func toList() -> [Any?] {
    return [
      accessKeyId,
      secretAccessKey,
      sessionToken,
      expirationEpochSeconds,
    ]
  }
  static func == (lhs: LivenessCredentialsMessage, rhs: LivenessCredentialsMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.accessKeyId, rhs.accessKeyId) && MessagesPigeonInternal.deepEquals(lhs.secretAccessKey, rhs.secretAccessKey) && MessagesPigeonInternal.deepEquals(lhs.sessionToken, rhs.sessionToken) && MessagesPigeonInternal.deepEquals(lhs.expirationEpochSeconds, rhs.expirationEpochSeconds)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LivenessCredentialsMessage")
    MessagesPigeonInternal.deepHash(value: accessKeyId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: secretAccessKey, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sessionToken, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: expirationEpochSeconds, hasher: &hasher)
  }

  public var description: String {
    return "LivenessCredentialsMessage(accessKeyId: \(String(describing: accessKeyId)), secretAccessKey: \(String(describing: secretAccessKey)), sessionToken: \(String(describing: sessionToken)), expirationEpochSeconds: \(String(describing: expirationEpochSeconds)))"
  }
}

/// The native SDK finished streaming. It carries no verdict on either
/// platform: the backend reads the result with GetFaceLivenessSessionResults.
///
/// Generated class from Pigeon that represents data sent in messages.
struct LivenessCompletionMessage: Hashable, CustomStringConvertible {
  var sessionId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LivenessCompletionMessage? {
    let sessionId = pigeonVar_list[0] as! String

    return LivenessCompletionMessage(
      sessionId: sessionId
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId
    ]
  }
  static func == (lhs: LivenessCompletionMessage, rhs: LivenessCompletionMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LivenessCompletionMessage")
    MessagesPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
  }

  public var description: String {
    return "LivenessCompletionMessage(sessionId: \(String(describing: sessionId)))"
  }
}

/// A native-side failure (SDK error, cancellation, or missing dependency).
///
/// Generated class from Pigeon that represents data sent in messages.
struct LivenessErrorMessage: Hashable, CustomStringConvertible {
  var code: LivenessErrorCode
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LivenessErrorMessage? {
    let code = pigeonVar_list[0] as! LivenessErrorCode
    let message = pigeonVar_list[1] as! String

    return LivenessErrorMessage(
      code: code,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
    ]
  }
  static func == (lhs: LivenessErrorMessage, rhs: LivenessErrorMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.code, rhs.code) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LivenessErrorMessage")
    MessagesPigeonInternal.deepHash(value: code, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
  }

  public var description: String {
    return "LivenessErrorMessage(code: \(String(describing: code)), message: \(String(describing: message)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return LivenessErrorCode(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return LivenessCredentialsMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return LivenessCompletionMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return LivenessErrorMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? LivenessErrorCode {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? LivenessCredentialsMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? LivenessCompletionMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? LivenessErrorMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Dart -> native. Called once, after the platform view is created and
/// credentials have been fetched. Receiving credentials is the signal for the
/// native side to present the liveness detector.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LivenessHostApi {
  func setCredentials(credentials: LivenessCredentialsMessage) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LivenessHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `LivenessHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LivenessHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let setCredentialsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rekognition_liveness.LivenessHostApi.setCredentials\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCredentialsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let credentialsArg = args[0] as! LivenessCredentialsMessage
        do {
          try api.setCredentials(credentials: credentialsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setCredentialsChannel.setMessageHandler(nil)
    }
  }
}
/// Dart -> native, app-wide (no channel suffix). The Android SDK does not ask
/// for the camera permission itself, so the app asks before showing the view.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LivenessPermissionApi {
  func requestCameraPermission(completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LivenessPermissionApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `LivenessPermissionApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LivenessPermissionApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let requestCameraPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rekognition_liveness.LivenessPermissionApi.requestCameraPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestCameraPermissionChannel.setMessageHandler { _, reply in
        api.requestCameraPermission { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestCameraPermissionChannel.setMessageHandler(nil)
    }
  }
}

/// Native -> Dart. Terminal callbacks; exactly one fires per session.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol LivenessFlutterApiProtocol {
  func onComplete(completion completionArg: LivenessCompletionMessage, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onError(error errorArg: LivenessErrorMessage, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class LivenessFlutterApi: LivenessFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onComplete(completion completionArg: LivenessCompletionMessage, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.rekognition_liveness.LivenessFlutterApi.onComplete\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([completionArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onError(error errorArg: LivenessErrorMessage, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.rekognition_liveness.LivenessFlutterApi.onError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
